{% set version = "0.2.3.dev2" %}
{% set name = "NanoCount" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: "pip install {{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -vv "
  entry_points:
    - NanoCount=NanoCount.__main__:main
  noarch: "python"

requirements:
  build:
    - python>=3.6
    - pip>=19.2.1
    - ripgrep>=11.0.1
  run:
    - tqdm>=4.51.0
    - numpy>=1.19.4
    - pysam>=0.16.0
    - pandas>=1.1.4
    - colorlog>=4.1.0

test:
  imports:
    - NanoCount.NanoCount
  commands:
    - NanoCount -h

about:
  home: https://github.com/a-slide/NanoCount/
  doc_url: https://adrienleger.com/NanoCount/
  license: MIT
  licence_url: https://mit-license.org/
  summary: NanoCount estimates transcripts abundance from Oxford Nanopore *direct-RNA sequencing* datasets, using an expectation-maximization approach like RSEM, Kallisto, salmon, etc to handle the uncertainty of multi-mapping reads

extra:
  author: Adrien Leger
  author_email: aleg@ebi.ac.uk
  author_url: https://adrienleger.com
