{% set version = "0.2.0" %}
{% set name = "NanoCount" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: "pip install {{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -vv "
  entry_points:
    - NanoCount=NanoCount.__main__:main
  noarch: "python"

requirements:
  build:
    - python>=3.6
    - pip>=19.2.1
    - ripgrep>=11.0.1
  run:
    - numpy>=1.14.0
    - pysam>=0.15.4
    - pandas>=1.0.3
    - tqdm>=4.46.0
    - colorlog>=4.1.0

test:
  imports:
    - NanoCount.NanoCount
    - NanoCount.Read
  commands:
    - NanoCount --help

about:
  home: "https://github.com/a-slide/NanoCount"
  license: "MIT"
  summary: "EM based transcripts abundance estimation from nanopore reads mapped to a transcriptome with minimap2"
