# Project information
site_name: NanoCount
site_description: NanoCount estimates transcripts abundance from Oxford Nanopore *direct-RNA sequencing* datasets, using an expectation-maximization approach like RSEM, Kallisto, salmon, etc to handle the uncertainty of multi-mapping reads
site_author: Adrien Leger
site_url: https://adrienleger.com/NanoCount/

# Repository
repo_name: 'a-slide/NanoCount'
repo_url: https://github.com/a-slide/NanoCount/

# Copyright
copyright: Copyright © 2020 Adrien Leger

# Navigation menu
nav:
    - Home: index.md
    - Installation instructions: installation.md
    - Advanced usage:
        - Input / Output files: nanocount_io.md
        - Command Line interface: NanoCount_CLI_usage.ipynb
        - Python API: NanoCount_API_usage.ipynb
    - Contributing: contributing.md
    - Code of conduct: code_of_conduct.md
    - Licence: licence.md

# Theme customization
theme:
    name: 'material'
    highlightjs: true
    font: false

markdown_extensions:
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: a-slide
      repo: NanoCount

plugins:
  - mknotebooks
