# Project information
site_name: __package_name__
site_description: __package_description__
site_author: __author_name__
site_url: __package_doc_url__

# Repository
repo_name: 'a-slide/pyBioTools'
repo_url: __package_url__

# Copyright
copyright: Copyright © 2020 __author_name__

# Navigation menu
nav:
    - Home: index.md
    - Installation instructions: installation.md
    - Advanced usage:
        - Input / Output files: nanocount_io.md
        - Command Line interface: NanoCount_CLI_usage.ipynb
        - Python API: NanoCount_API_usage.ipynb
    - Contributing: contributing.md
    - Code of conduct: code_of_conduct.md
    - Licence: licence.md
    - Changelog: changelog.md


# Theme customization
theme:
    name: 'material'
    highlightjs: true
    font: false

markdown_extensions:
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: a-slide
      repo: NanoCount

plugins:
  - mknotebooks
